from mypkg import activewindow
from mypkg import computername
from mypkg import core
from mypkg import disksize
from mypkg import file
from mypkg import macadress
from mypkg import memory
from mypkg import process
from mypkg import registry